# basic options
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: A wonderful site
twitter_username: humbleb38117697
github_username:  mm5t8

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
